pipeline {
    agent any

    tools {
        jdk 'JDK'
        maven 'MAVEN'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/panditk/HelloWorld.git',
                credentialsId: '5535a237-22cc-4497-9101-75338c620d3b'
            }
        }

        stage('Build') {
            steps {
                dir('Test2') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Test2'){
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Test2'){
                sh 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
